#!/usr/bin/env bash
# build_and_push.sh — build Lambda container + push to ECR
# Usage (M6 [USER_RUN]):
#   bash infra/lambda/build_and_push.sh
#
# Prerequisites:
#   - AWS credentials exported (ACCOUNT_ID / REGION match Learner Lab)
#   - Docker daemon running
#   - ECR repo tdcs-dl-cleaner already exists
#     (aws ecr create-repository --repository-name tdcs-dl-cleaner --region us-east-1)
set -euo pipefail

ACCOUNT_ID="${ACCOUNT_ID:-654485222392}"
REGION="${REGION:-us-east-1}"
REPO="${REPO:-tdcs-dl-cleaner}"
ECR_URI="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"

cd "$(dirname "$0")"

# -----------------------------------------------------------------------
# F-H4 fix（PLAN_E9 gate、見 workflow/logs/實驗紀錄7_1.md F-H4）：
# 每次部署用「不可變、唯一」的 image tag、不要再固定推 :latest。
#
# 為什麼：Lambda 的 image_uri 綁 :latest 時、push 新 image 後 image_uri 字串沒變
#   → `terraform apply` 偵測 diff = 0 → Lambda 繼續跑「上一版」image（鬼打牆：
#   「我明明改了 handler、Lambda 還跑舊 code」）。Lambda 是按 push 當下 digest 綁定、
#   不會自動追 latest。
#
# 解法（不動 lambda.tf）：tag = git short SHA、寫進 ../terraform/image_tag.auto.tfvars
#   餵既有的 var.lambda_image_tag（variables.tf 已預留、description 寫 "commit SHA"）。
#   terraform 會自動載入 *.auto.tfvars → image_uri 字串隨每次部署改變 → in-place 更新
#   Lambda code。部署者只要跑 `terraform apply`、不必記 -replace、不必手改 .tf。
#
# 為什麼選這個方案而非 (a) digest pin 或 (c) terraform apply -replace：
#   - (c) -replace：要部署者每次記得帶 magic flag、忘了跑純 apply 又靜默回舊 image
#     （違反「6 個月後別人接手要能直接跑」）、且 destroy+create 比 in-place 重。
#   - (a) @sha256 digest pin：最嚴謹、但要改 lambda.tf line 17（與並行 worker 衝突風險）
#     且 digest 不可讀。
#   - 本方案：達成 (a) 的目標（terraform 偵測得到 image 變更、純 apply 即生效）、
#     但 blast radius = (c)（只動本腳本 + README）、tag 還是人看得懂的 git SHA。
#
# TAG 可由環境變數覆寫（CI / 指定版本回滾）：`TAG=v1.2.3 bash build_and_push.sh`
# -----------------------------------------------------------------------
if [[ -z "${TAG:-}" ]]; then
  GIT_SHA="$(git rev-parse --short=12 HEAD 2>/dev/null || echo nogit)"
  if [[ -n "$(git status --porcelain 2>/dev/null)" ]]; then
    # working tree 有未提交變更 → 補時間戳、避免同一 SHA 的兩次 dirty 部署撞同一 tag
    # （撞 tag 又會重現 F-H4 的 diff=0 鬼打牆）。clean tree 則用純 SHA、ECR 不長垃圾。
    TAG="${GIT_SHA}-dirty-$(date +%Y%m%d%H%M%S)"
  else
    TAG="${GIT_SHA}"
  fi
fi
echo "[tag] image tag for this deploy: ${TAG}"

echo "[1/5] esbuild — bundle src/index.ts → dist/index.js ..."
npm install
npx esbuild src/index.ts \
  --bundle \
  --platform=node \
  --target=node20 \
  --outfile=dist/index.js \
  --format=cjs \
  --external:nodejs-polars \
  --external:@aws-sdk/*

echo "[2/5] docker build ..."
# --provenance=false --platform=linux/amd64：強制單一 Docker v2 manifest、避免
# Docker Desktop 4.x+ buildx 預設輸出 OCI manifest list + attestation manifest、
# 而 Lambda runtime 拒收 OCI manifest（InvalidParameterValueException：The image
# manifest, config or layer media type ... is not supported）。
# 2026-06-04 PLAN_E7 M6 deploy_worker 實證 — 沒加會在 terraform apply 卡 Lambda 步。
docker build --provenance=false --platform=linux/amd64 -t "${REPO}:${TAG}" .

echo "[3/5] ECR login ..."
aws ecr get-login-password --region "${REGION}" \
  | docker login --username AWS --password-stdin "${ECR_URI}"

echo "[4/5] tag + push（唯一 tag + 同步更新 latest 供人工瀏覽/回滾參考）..."
# 部署綁定的是「唯一 tag」（image_tag.auto.tfvars 寫的就是它）；
# latest 只是給人 `docker pull ...:latest` 看最新版用、不是 Lambda 綁定對象。
docker tag "${REPO}:${TAG}" "${ECR_URI}/${REPO}:${TAG}"
docker push "${ECR_URI}/${REPO}:${TAG}"
docker tag "${REPO}:${TAG}" "${ECR_URI}/${REPO}:latest"
docker push "${ECR_URI}/${REPO}:latest"

echo "[5/5] write ../terraform/image_tag.auto.tfvars（餵 var.lambda_image_tag）..."
# terraform 自動載入 *.auto.tfvars；下一步純跑 `terraform apply` 即把 Lambda 指到此 tag。
TFVARS="../terraform/image_tag.auto.tfvars"
cat > "${TFVARS}" <<EOF
# AUTO-GENERATED by infra/lambda/build_and_push.sh — 請勿 commit（部署機本地、已 gitignore）。
# 把 Lambda 釘在這次剛 push 的 image tag（F-H4 fix）。terraform 自動載入 *.auto.tfvars。
lambda_image_tag = "${TAG}"
EOF
echo "wrote ${TFVARS}: lambda_image_tag = \"${TAG}\""

echo ""
echo "DONE: ${ECR_URI}/${REPO}:${TAG}"
echo "下一步：cd ../terraform && terraform apply"
echo "（image_tag.auto.tfvars 已寫好、terraform 會自動帶 tag = ${TAG}、不必手加 -var/-replace）"
